# Generated by Django 4.2.3 on 2023-11-09 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0002_alter_student_teacher_delete_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('grade', models.IntegerField(default=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_app.student')),
            ],
        ),
    ]
